# Config Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: clinic-booking
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: clinic-booking/config-service:latest
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 5
---
# Config Service
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: clinic-booking
spec:
  selector:
    app: config-service
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP
