# Doctor Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: clinic-booking
  labels:
    app: doctor-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
      - name: doctor-service
        image: clinic-booking/doctor-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/doctor_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "clinic_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "clinic_password"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery-service:8761/eureka/"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 5
---
# Doctor Service
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: clinic-booking
spec:
  selector:
    app: doctor-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
