spring:
  application:
    name: appointment-service

  # Profile-based Config Service URL
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888"

  cloud:
    config:
      enabled: true
      fail-fast: false

  # Database configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/appointment_db?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

server:
  port: 8082

logging:
  level:
    com.myclinic.appointment: DEBUG