server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared-config
        git:
          uri: file://${user.home}/clinic-config-repo
          search-paths: shared-config
          default-label: main

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.myclinic.config: DEBUG
    org.springframework.cloud.config: DEBUG
