server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared-config

# Disable Eureka for Config Service
eureka:
  client:
    enabled: false
  instance:
    enabled: false

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.myclinic.config: DEBUG
    org.springframework.cloud.config: DEBUG
